/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import ControleClass.ControleLivro;
import entidades.Livro;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author NICCLABPROF
 */
public class TelaCadastroLivro extends javax.swing.JPanel {
    ControleLivro opLivro =  new ControleLivro();
    int idint =0;
    
    /**
     * Creates new form TelaCadastroLivro
     */
    public TelaCadastroLivro() {
        initComponents();
        jTableLivros.setModel(opLivro);
        jButtonExcluir.setEnabled(false);
        jButtonInformacaoLivro.setEnabled(false);
        jButtonAtualizar.setEnabled(false);
        jButtonSelecionar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabelVolume = new javax.swing.JLabel();
        jTextAutor = new javax.swing.JTextField();
        jButtonInformacaoLivro = new javax.swing.JButton();
        jLabelEdicao = new javax.swing.JLabel();
        jTextVolume = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jTextEdicao = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        jLabelAutor = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabelEditora = new javax.swing.JLabel();
        jTextEditora = new javax.swing.JTextField();
        jLabelNumeroPag = new javax.swing.JLabel();
        jTextEstoqueDisponivel = new javax.swing.JTextField();
        jLabelID6 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jButtonSelecionar = new javax.swing.JButton();

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLivros);

        jLabel3.setText("Genero");

        jLabelVolume.setText("Volume");

        jButtonInformacaoLivro.setText("Visualizar Informações do Livro");
        jButtonInformacaoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacaoLivroActionPerformed(evt);
            }
        });

        jLabelEdicao.setText("Edição");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelTitulo.setText("Titulo");

        jButtonAtualizar.setText("Editar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jLabelAutor.setText("Autor");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terror", "Romantico", "Ficção", "Biografia" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        jLabelEditora.setText("Editora");

        jLabelNumeroPag.setText("Número Disponivel");

        jLabelID6.setText("Id Livro");

        jLabelID.setText("00000");

        jButtonSelecionar.setText("Selecionar Livro");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTitulo)
                                        .addGap(177, 177, 177)
                                        .addComponent(jLabelAutor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVolume))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEdicao)
                                            .addComponent(jTextEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEditora)
                                            .addComponent(jTextEditora))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextEstoqueDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNumeroPag)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelID6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdicionar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAtualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSelecionar)
                                .addGap(88, 88, 88)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInformacaoLivro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelAutor)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelVolume)
                                    .addComponent(jLabelEdicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNumeroPag)
                                    .addComponent(jLabelID6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextEstoqueDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelID)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonSelecionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonInformacaoLivro)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        
        
        jLabelID.setText("000"+Integer.toString(idint));
        
        try {
        /////////////////////////////////////////////////////////////    
        String titulo = jTextTitulo.getText();
        if (jTextTitulo.getText() == null || jTextTitulo.getText().equals("")) {
            jLabelTitulo.setForeground(Color.red);
        }else{
            jLabelTitulo.setForeground(Color.BLACK);
        }        
        String autor = jTextAutor.getText();
        if (jTextAutor.getText() == null || jTextAutor.getText().equals("")) {
            jLabelAutor.setForeground(Color.red);
        }else{            
            jLabelAutor.setForeground(Color.BLACK);
        }
        ///////////////////////////////////////////////////////////
        int edicao = 0;
        if (jTextEdicao.getText() == null || jTextEdicao.getText().equals("")) {
            jLabelEdicao.setForeground(Color.red);
        }else{            
            jLabelEdicao.setForeground(Color.BLACK);
            edicao = Integer.parseInt(jTextEdicao.getText());
        }
        int volume = 0;
        if (jTextVolume.getText() == null || jTextVolume.getText().equals("")) {
            jLabelVolume.setForeground(Color.red);
        }else{            
            jLabelVolume.setForeground(Color.BLACK);
            volume = Integer.parseInt(jTextVolume.getText());
        }
        String editora = "";
        if (jTextEditora.getText() == null || jTextEditora.getText().equals("")) {
            jLabelEditora.setForeground(Color.red);
        }else{            
            jLabelEditora.setForeground(Color.BLACK);
            editora = jTextEditora.getText();
        }
        int nPaginas = 0;
        if (jTextEstoqueDisponivel.getText() == null || jTextEstoqueDisponivel.getText().equals("")) {
            jLabelNumeroPag.setForeground(Color.red);
        }else{            
            jLabelNumeroPag.setForeground(Color.BLACK);
            nPaginas = Integer.parseInt(jTextEstoqueDisponivel.getText());
        }
        int id = Integer.parseInt(jLabelID.getText());   
        
        int generoInt = jComboBoxGenero.getSelectedIndex();//retorna a index da posicao escolhida do livro
        String generoString = "";
        switch (generoInt) {//define a escolha do usuario na variavel
            case 0:
                generoString = "Terror";
                break;
            case 1:
                generoString = "Romantico";
                break;
            case 2:
                generoString = "Ficção";
                break;
            case 3:
                generoString = "Biografia";
                break;
        }
        if(!(jTextTitulo.getText() == null || jTextTitulo.getText().equals(""))&&!(jTextAutor.getText() == null || jTextAutor.getText().equals(""))&&!(jTextEdicao.getText() == null || jTextEdicao.getText().equals(""))&&!(jTextVolume.getText() == null || jTextVolume.getText().equals(""))&&!(jTextEditora.getText() == null || jTextEditora.getText().equals(""))&&!(jTextEstoqueDisponivel.getText() == null || jTextEstoqueDisponivel.getText().equals(""))){
            Livro livroNv = new Livro(autor, editora, edicao, volume, generoString, nPaginas, id, titulo);
            boolean conf =  opLivro.addRow(livroNv);
            jTextAutor.setText("");
            jTextEdicao.setText("");
            jTextEditora.setText("");
            jTextEstoqueDisponivel.setText("");
            jTextTitulo.setText("");
            jTextVolume.setText("");
            if(conf == false){
                    JOptionPane.showMessageDialog(null, " Livro cadastrado com Sucesso!!!", "Confirmação Cadastro Livro!", JOptionPane.INFORMATION_MESSAGE);
                    idint++;
                    jButtonSelecionar.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Já existe um livro com o titulo informado!!!", " Erro!!!", JOptionPane.INFORMATION_MESSAGE);
                }
            
        }       
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Não foi possivel adicionar o livro por conta do erro: " + e, "Erro", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableLivros.getSelectedRow() != -1) {      
            int conf = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_OPTION);
            if(conf== JOptionPane.YES_OPTION){
                if(opLivro.removeRow(jTableLivros.getSelectedRow())){
                    jTextAutor.setText("");
                    jTextEdicao.setText("");
                    jTextEditora.setText("");
                    jTextEstoqueDisponivel.setText("");
                    jTextTitulo.setText("");
                    jTextVolume.setText("");
                    JOptionPane.showMessageDialog(null, "Livro Excluido com Sucesso!!!", "Sucesso!!", JOptionPane.INFORMATION_MESSAGE);
                    jButtonExcluir.setEnabled(false);
                    jButtonAtualizar.setEnabled(false);
                    
                }
            }
            
            
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if (jTableLivros.getSelectedRow() != -1) {
            String titulo = jTextTitulo.getText();
            String autor = jTextAutor.getText();
            int volume = Integer.parseInt(jTextVolume.getText());
            int edicao = Integer.parseInt(jTextEdicao.getText());
            String editora = jTextEditora.getText();
            int estoque = Integer.parseInt(jTextEstoqueDisponivel.getText());
            int id = Integer.parseInt(jLabelID.getText());
             int generoInt = jComboBoxGenero.getSelectedIndex();//////swict
            String generoString = "";
            switch (generoInt) {
                case 0:
                generoString = "Terror";
                    break;
                case 1:
                    generoString = "Romantico";
                    break;
                case 2:
                    generoString = "Ficção";
                    break;
                case 3:
                    generoString = "Biografia";
                    break;
            }
            Livro livroEditar = new Livro(autor, editora, edicao, volume, generoString, estoque, id, titulo);
            int conf = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja editar este Livro?", "Confrimação de edição!", JOptionPane.YES_OPTION);
            if(conf == JOptionPane.YES_OPTION){
                opLivro.editarLivro(jTableLivros.getSelectedRow(), livroEditar);
                jTextAutor.setText("");
                jTextEdicao.setText("");
                jTextEditora.setText("");
                jTextEstoqueDisponivel.setText("");
                jTextTitulo.setText("");
                jTextVolume.setText("");
                JOptionPane.showMessageDialog(null, "Livro Editado com Sucesso!!!", "Sucesso!!", JOptionPane.INFORMATION_MESSAGE);
                jButtonAtualizar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
            }
            
            
            
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jButtonInformacaoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacaoLivroActionPerformed
        if(jTableLivros.getSelectedRow() != -1){
            TelaInformacaoLivro op = new TelaInformacaoLivro(opLivro.getSelectedValue(jTableLivros.getSelectedRow()));
            JFrame Jf  = new JFrame();
            Jf.setSize(400, 400);
            Jf.setLocationRelativeTo(null);
            Jf.setContentPane(op);
            Jf.setVisible(true);
            Jf.setResizable(false);
            
        }
    }//GEN-LAST:event_jButtonInformacaoLivroActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        if(jTableLivros.getSelectedRow() != -1){
            Livro livroEditar = opLivro.getSelectedValue(jTableLivros.getSelectedRow());
            jTextAutor.setText(livroEditar.getAutor());
            jTextEdicao.setText(Integer.toString(livroEditar.getEdicao()));
            jTextEditora.setText(livroEditar.getEditora());
            jTextEstoqueDisponivel.setText(Integer.toString(livroEditar.getQuantidadesDisponivel()));
            jTextTitulo.setText(livroEditar.getTitulo());
            jTextVolume.setText(Integer.toString(livroEditar.getVolume()));
            jLabelID.setText(Integer.toString(livroEditar.getIdLivro()));
            jButtonExcluir.setEnabled(true);
            jButtonInformacaoLivro.setEnabled(true);
            jButtonAtualizar.setEnabled(true);

        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInformacaoLivro;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEdicao;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID6;
    private javax.swing.JLabel jLabelNumeroPag;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVolume;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTextField jTextAutor;
    private javax.swing.JTextField jTextEdicao;
    private javax.swing.JTextField jTextEditora;
    private javax.swing.JTextField jTextEstoqueDisponivel;
    private javax.swing.JTextField jTextTitulo;
    private javax.swing.JTextField jTextVolume;
    // End of variables declaration//GEN-END:variables
}
