/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import entidades.Aluno;
import ControleClass.ControleAluguelLivro;
import ControleClass.ControleLivro;
import entidades.Livro;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Paulo Victor
 */
public class TelaDevolverLivro extends javax.swing.JPanel {
    ControleAluguelLivro op = new ControleAluguelLivro();
    Aluno alunoPadraoClase = null;
    List<Livro> pp = null;
    /**
     * Creates new form TelaDevolverLivro
     */
    public TelaDevolverLivro(Aluno alunoInformacoes) {
        initComponents();
        alunoPadraoClase = alunoInformacoes;
        jLabelNomeAluno.setText(alunoInformacoes.getNome());
        jLabelMatriculaAluno.setText(Integer.toString(alunoInformacoes.getMatricula()));
        jLabelLivro1.setVisible(false);
        jLabelLivro2.setVisible(false);
        jLabelLivro3.setVisible(false);
        jLabelLivro4.setVisible(false);
        
        int size =-1;
        
        try {
            
        if(op.getSelectValue(alunoInformacoes.getMatricula()) != null){
           pp = op.getSelectValue(alunoInformacoes.getMatricula());
           size = pp.size();
        }
        }catch (Exception e) {          
            JOptionPane.showMessageDialog(null, "O usuario não pussui nenhum livro!", "Obsevação!!", JOptionPane.INFORMATION_MESSAGE);
                   
        }
        if(size != -1){
            for(int i =0; i<size;i++){
                switch(i){
                    case 0:
                        jLabelLivro1.setVisible(true);
                         jLabelLivro1.setText("0 - "+pp.get(0).getTitulo());
                        break;
                    case 1:
                        jLabelLivro2.setVisible(true);
                         jLabelLivro2.setText("1 - "+pp.get(1).getTitulo());  
                        break;
                    case 2:
                        jLabelLivro3.setVisible(true);
                         jLabelLivro3.setText("2 - "+pp.get(2).getTitulo());  
                        break;
                    case 3:
                        jLabelLivro4.setVisible(true);
                         jLabelLivro4.setText("3 - "+pp.get(3).getTitulo());  
                        break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLivro1 = new javax.swing.JLabel();
        jLabelNomeAluno = new javax.swing.JLabel();
        jLabelMatriculaAluno = new javax.swing.JLabel();
        jLabelLivro2 = new javax.swing.JLabel();
        jLabelLivro4 = new javax.swing.JLabel();
        jLabelLivro3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIdLivro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Nome Aluno:");

        jLabel2.setText("Matricula");

        jLabel3.setText("Lista de Livro");

        jLabelLivro1.setText("jLabel4");

        jLabelNomeAluno.setText("jLabel5");

        jLabelMatriculaAluno.setText("jLabel6");

        jLabelLivro2.setText("jLabel7");

        jLabelLivro4.setText("jLabel7");

        jLabelLivro3.setText("jLabel4");

        jLabel10.setText("Digite o id do livro que você deseja devolver!");

        jButton1.setText("Devolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelLivro1))
                        .addComponent(jLabelLivro2)
                        .addComponent(jLabelLivro3)
                        .addComponent(jLabelLivro4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMatriculaAluno)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelNomeAluno))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel10)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNomeAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelMatriculaAluno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelLivro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLivro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLivro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLivro4)
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int id = Integer.parseInt(jTextFieldIdLivro.getText());
        boolean conf = op.removerAluguel(alunoPadraoClase, pp.get(id));       
        if(conf){
                JOptionPane.showMessageDialog(null, "Sucesso", "Livro Devolvido!!! Pode fechar a pagina!!", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "erro", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        /*if(id  ){           
            
        }else{
             JOptionPane.showMessageDialog(null, "Erro", "Id invalido!!", JOptionPane.INFORMATION_MESSAGE);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLivro1;
    private javax.swing.JLabel jLabelLivro2;
    private javax.swing.JLabel jLabelLivro3;
    private javax.swing.JLabel jLabelLivro4;
    private javax.swing.JLabel jLabelMatriculaAluno;
    private javax.swing.JLabel jLabelNomeAluno;
    private javax.swing.JTextField jTextFieldIdLivro;
    // End of variables declaration//GEN-END:variables
}
