/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import ControleClass.ControleLivro;
import entidades.Aluno;
import ControleClass.ControleAluguelLivro;
import entidades.aluguelLivro;
import entidades.Livro;
import javax.swing.JOptionPane;
/**
 *
 * @author Paulo Victor
 */
public class TelaEmprestarLivro extends javax.swing.JPanel {
    ControleLivro modelTabela = new ControleLivro();
    ControleAluguelLivro md= new ControleAluguelLivro();
    Aluno padrao;
    /**
     * Creates new form EmprestarLivro
     */
    public TelaEmprestarLivro(Aluno al) {
        padrao = al;
        initComponents();
        jTableLivros.setModel(modelTabela);
        jLabelNome.setText(al.getNome());
        jLabelMatricula.setText(Integer.toString(al.getMatricula()));
        jLabelCpf.setText(al.getCpf());
        jLabelLimiteLivro.setText("4");
        jLabelQuantidade.setText(Integer.toString(md.valorLivrosPegos(al)));
        
        aluguelLivro alu = new aluguelLivro();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelLimiteLivro = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLivros);

        jLabel1.setText("Nome do Aluno:");

        jLabel2.setText("Matricula");

        jLabel3.setText("CPF:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelNome.setText("nome");

        jLabelMatricula.setText("matricula");

        jLabelCpf.setText("cpf");

        jLabel4.setText("Limite Livro");

        jLabel5.setText("Quantidade de livro já pegos:");

        jLabelLimiteLivro.setText("Limite");

        jLabelQuantidade.setText("quant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpf)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelMatricula))
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQuantidade)
                                    .addComponent(jLabelLimiteLivro)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalvar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelLimiteLivro))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelMatricula)
                    .addComponent(jLabel5)
                    .addComponent(jLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        if(jTableLivros.getSelectedRow() != -1){
                Livro p = modelTabela.getSelectedValue(jTableLivros.getSelectedRow());                
                boolean confEstoque = modelTabela.estoqueDisponivel(p);
                if(confEstoque == true){
                       
                        boolean con = md.adicionarAluguel(padrao, 4, p);
                        int conf = JOptionPane.showConfirmDialog(null, "Tem certeza em emprestar esse Livro?", "Confirmação", JOptionPane.YES_OPTION);
                        if(con && conf == JOptionPane.YES_OPTION){  
                             modelTabela.diminuirEstoque(p);
                            int valorLimte = md.valorLivrosPegos(padrao);
                            if(valorLimte<=4){
                                JOptionPane.showMessageDialog(null, "Sucesso", "Livro Emprestado!!!", JOptionPane.INFORMATION_MESSAGE);
                                jLabelQuantidade.setText(Integer.toString(md.valorLivrosPegos(padrao)));

                            }else{
                                JOptionPane.showMessageDialog(null, "Você atingiu o limite de aluguel, devolva um, para poder pegar outro!!!", "Erro!!", JOptionPane.INFORMATION_MESSAGE);
                            }  
                        }               
                }
                else{   
                 JOptionPane.showMessageDialog(null, "Esse livro não tem estoque para ser alugado!!!!!", "Erro!!", JOptionPane.INFORMATION_MESSAGE);
                    
                }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelLimiteLivro;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    // End of variables declaration//GEN-END:variables
}
