/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import entidades.Livro;
/**
 *
 * @author Paulo Victor
 */
public class TelaInformacaoLivro extends javax.swing.JPanel {

    /**
     * Creates new form TelaInformacaoLivro
     */
    public TelaInformacaoLivro(Livro livroInformacoes) {
        initComponents();
        jLabelAutor.setText(livroInformacoes.getAutor());
        jLabelEdicao.setText(livroInformacoes.getEditora());
        jLabelEditora.setText(livroInformacoes.getEditora());
        jLabelGenero.setText(livroInformacoes.getGenero());
        jLabelIdLivro.setText(Integer.toString(livroInformacoes.getIdLivro()));
        jLabelQuantidadesDisponiveis.setText(Integer.toString(livroInformacoes.getQuantidadesDisponivel()));
        jLabelVolume.setText(Integer.toString(livroInformacoes.getVolume()));
        jLabelTitulo.setText(livroInformacoes.getTitulo());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelQuantidadesDisponiveis = new javax.swing.JLabel();
        jLabelEditora = new javax.swing.JLabel();
        jLabelVolume = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelEdicao = new javax.swing.JLabel();
        jLabelIdLivro = new javax.swing.JLabel();

        jLabel1.setText("Autor");

        jLabel2.setText("Titulo");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Editora");

        jLabel5.setText("Volume");

        jLabel6.setText("Genero");

        jLabel7.setText("Id Livro");

        jLabel8.setText("Edição");

        jLabelAutor.setText("jLabel9");

        jLabelTitulo.setText("jLabel9");

        jLabelQuantidadesDisponiveis.setText("jLabel9");

        jLabelEditora.setText("jLabel9");

        jLabelVolume.setText("jLabel9");

        jLabelGenero.setText("jLabel9");

        jLabelEdicao.setText("jLabel9");

        jLabelIdLivro.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdLivro)
                    .addComponent(jLabelEdicao)
                    .addComponent(jLabelGenero)
                    .addComponent(jLabelVolume)
                    .addComponent(jLabelEditora)
                    .addComponent(jLabelQuantidadesDisponiveis)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelAutor))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelQuantidadesDisponiveis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelGenero))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelEdicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelIdLivro))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEdicao;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelIdLivro;
    private javax.swing.JLabel jLabelQuantidadesDisponiveis;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVolume;
    // End of variables declaration//GEN-END:variables
}
