/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import entidades.Aluno;
import ControleClass.ControleAluno;
import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NICCLABPROF
 */
public class TelaCadastroAluno extends javax.swing.JPanel {
    ControleAluno op = new ControleAluno();
    //
    /**
     * Creates new form TelaCadastroAluno
     */
    public TelaCadastroAluno() {
        initComponents();
        jTableAluno.setModel(op);
        jButtonAtualizar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSelecionar.setEnabled(false);
        jButtonDevolucao.setEnabled(false);
        jButtonEmprestar.setEnabled(false);
        jButtonInformacaoAluno.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jLabelContato = new javax.swing.JLabel();
        jButtonInformacaoAluno = new javax.swing.JButton();
        jLabelEndereco = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonEmprestar = new javax.swing.JButton();
        jButtonDevolucao = new javax.swing.JButton();
        jTextNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jTextMatricula = new javax.swing.JTextField();
        jTextEnderrco = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jTextCpf = new javax.swing.JFormattedTextField();
        jTextContato = new javax.swing.JFormattedTextField();
        jButtonSelecionar = new javax.swing.JButton();

        jLabelMatricula.setText("Matricula");

        jLabelContato.setText("Contato (opcional)");

        jButtonInformacaoAluno.setText("Visualizar Informações do Aluno");
        jButtonInformacaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacaoAlunoActionPerformed(evt);
            }
        });

        jLabelEndereco.setText("Endereco (opcional)");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Editar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonEmprestar.setText("Emprestar Livro");
        jButtonEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestarActionPerformed(evt);
            }
        });

        jButtonDevolucao.setText("Devolver Livro");
        jButtonDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolucaoActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAluno);

        jLabelNome.setText("Nome");

        jLabelCpf.setText("Cpf (opcional)");

        try {
            jTextCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonSelecionar.setText("Selecionar Aluno");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jButtonEmprestar)
                                .addGap(44, 44, 44)
                                .addComponent(jButtonDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonInformacaoAluno)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelContato)
                                    .addGap(115, 115, 115))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextContato)
                                    .addGap(26, 26, 26))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEndereco)
                            .addComponent(jTextEnderrco, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jLabelCpf)
                            .addComponent(jTextCpf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula)
                            .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButtonAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtualizar)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContato)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEnderrco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonSelecionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEmprestar)
                    .addComponent(jButtonDevolucao)
                    .addComponent(jButtonInformacaoAluno))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        try {
        String nome = "";
        if(jTextNome.getText() == null || jTextNome.getText().equals("")){
            jLabelNome.setForeground(Color.red);
        }
        else{
            jLabelNome.setForeground(Color.BLACK);
            nome = jTextNome.getText();
        }
        String cpf = "";       
        cpf = jTextCpf.getText();         
        String endereco = "";       
        endereco = jTextEnderrco.getText();
        
        String contato = "";
        if(jTextContato.getText() == null || jTextContato.getText().equals("")){
            jLabelContato.setForeground(Color.red);
        }else{
            jLabelContato.setForeground(Color.BLACK);
            contato = jTextContato.getText();
        }
        int matricula = 0;
        if(jTextMatricula.getText() == null || jTextMatricula.getText().equals("")){
            jLabelMatricula.setForeground(Color.red);
        }
        else{
            jLabelMatricula.setForeground(Color.BLACK);
            matricula = Integer.parseInt(jTextMatricula.getText());
        }
        if(!(jTextNome.getText() == null || jTextNome.getText().equals(""))&&!(jTextMatricula.getText() == null || jTextMatricula.getText().equals(""))){
            Aluno al = new Aluno(nome, cpf, endereco, contato, matricula);
            jTextCpf.setText("");
            jTextEnderrco.setText("");
            jTextNome.setText("");
            jTextContato.setText("");
            jTextMatricula.setText("");
            al.setEndereco(endereco);
            boolean conf =  op.addRow(al);
                if(conf == false){
                    JOptionPane.showMessageDialog(null, " Aluno cadastrado com Sucesso!!!", "Confirmação Cadastro Aluno", JOptionPane.INFORMATION_MESSAGE);
                    jButtonSelecionar.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Já existe um aluno com a matricula ou cpf informados!!!", " Erro!!!", JOptionPane.INFORMATION_MESSAGE);
                }
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar o Aluno!! erro: " + e, "erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableAluno.getSelectedRow() != -1) {
            int conf = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse aluno?", "Confirmação", JOptionPane.YES_OPTION);
            if(conf == JOptionPane.YES_OPTION){
                op.removeRow(jTableAluno.getSelectedRow());
                jButtonExcluir.setEnabled(false);
                jButtonAtualizar.setEnabled(false);
                jTextCpf.setText("");
                jTextEnderrco.setText("");
                jTextNome.setText("");
                jTextContato.setText("");
                jTextMatricula.setText("");
            }            
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if(jTableAluno.getSelectedRow() != -1){
        String nome = jTextNome.getText();
        String cpf = jTextCpf.getText();
        String endereco = jTextEnderrco.getText();
        String contato = jTextContato.getText();
        int matricula = Integer.parseInt(jTextMatricula.getText());
        Aluno aluEditado = new Aluno(nome, cpf, endereco, contato, matricula);
        int confirmacaoEditarAluno = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar esse Aluno?", "Confirmacao", JOptionPane.YES_OPTION);
        if(confirmacaoEditarAluno == JOptionPane.YES_OPTION){
            op.editarAluno(jTableAluno.getSelectedRow(), aluEditado);
            jTextCpf.setText("");
            jTextEnderrco.setText("");
            jTextNome.setText("");
            jTextContato.setText("");
            jTextMatricula.setText("");
            jButtonAtualizar.setEnabled(false);
            JOptionPane.showMessageDialog(null, " Aluno Editado com Sucesso!!!", "Confirmação editação Aluno", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonInformacaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacaoAlunoActionPerformed
        if(jTableAluno.getSelectedRow() != -1){            
            TelaInformacaoAluno inf = new TelaInformacaoAluno(op.getSelectedValue(jTableAluno.getSelectedRow()), jTableAluno.getSelectedRow());
            JFrame p = new JFrame();
            p.setSize(400,400);
            p.setLocationRelativeTo(null);
            p.setContentPane(inf);
            p.setVisible(true);
            p.setResizable(false);           
            
        }
    }//GEN-LAST:event_jButtonInformacaoAlunoActionPerformed

    private void jButtonEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestarActionPerformed
       
        if(jTableAluno.getSelectedRow() != -1){            
            TelaEmprestarLivro frameEmprestar = new TelaEmprestarLivro(op.getSelectedValue(jTableAluno.getSelectedRow()));
            JFrame p = new JFrame();
            p.setSize(600, 520);
            p.setLocationRelativeTo(null);
            p.setContentPane(frameEmprestar);
            p.setVisible(true);
            p.setResizable(false);
       }
           
       
    }//GEN-LAST:event_jButtonEmprestarActionPerformed

    private void jButtonDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolucaoActionPerformed
       if(jTableAluno.getSelectedRow() != -1){
           TelaDevolverLivro frameDevolver = new TelaDevolverLivro(op.getSelectedValue(jTableAluno.getSelectedRow()));
           JFrame p = new JFrame();
            p.setSize(471, 386);
            p.setLocationRelativeTo(null);
            p.setContentPane(frameDevolver);
            p.setVisible(true);
            p.setResizable(false);
       }
    }//GEN-LAST:event_jButtonDevolucaoActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        if (jTableAluno.getSelectedRow() != -1) {
            
            Aluno a =  op.getSelectedValue(jTableAluno.getSelectedRow());
            jTextNome.setText(a.getNome());
            jTextEnderrco.setText(a.getEndereco());
            jTextCpf.setText(a.getCpf());
            jTextMatricula.setText(Integer.toString(a.getMatricula()));
            jTextContato.setText(a.getContato());       
            jButtonAtualizar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonDevolucao.setEnabled(true);
            jButtonEmprestar.setEnabled(true);
            jButtonInformacaoAluno.setEnabled(true);

        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonDevolucao;
    private javax.swing.JButton jButtonEmprestar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInformacaoAluno;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JLabel jLabelContato;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JFormattedTextField jTextContato;
    private javax.swing.JFormattedTextField jTextCpf;
    private javax.swing.JTextField jTextEnderrco;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
